Repository EMMC-ASBL/oteapi-core, pull requests merged in 2022-01, with the labels that each got.

#1 Release and tests CD/CI
  .github/workflows/cd_release.yml
  .github/workflows/ci_tests.yml
  .github/workflows/utils/release_tag_msg.txt
  .github/workflows/utils/update_publish.sh
  MANIFEST.in
  oteapi/__init__.py
  requirements.txt
  setup.py
  tasks.py
Labels: enhancement

#28 Updated cd_release.yml to python 3.9
  .github/workflows/cd_release.yml
Labels: BLOCKING

#41 Install the `dev` extra in publish workflow
  .github/workflows/cd_release.yml
Labels: BLOCKING

#45 [Auto-generated] Update dependencies
  .pre-commit-config.yaml
  requirements.txt
  requirements_dev.txt
Labels: CI/CD
