Repository EMMC-ASBL/oteapi-core, pull requests merged in 2023-10, with the labels that each got.

#352 [Auto-generated] Update dependencies
  .pre-commit-config.yaml
Labels: CI/CD

#345 Update README with info about this branch
  README.md
  docs/index.md
Labels: pydantic-v1

#350 Update release and tests CI/CD workflows
  .github/workflows/cd_release.yml
  .github/workflows/ci_automerge_dependabot.yml
  .github/workflows/ci_cd_updated_master.yml
  .github/workflows/ci_check_dependencies.yml
  .github/workflows/ci_dependabot.yml
  .github/workflows/ci_tests.yml
  .pre-commit-config.yaml
Labels: pydantic-v1

#358 [Auto-generated] Update dependencies
  .github/workflows/cd_release.yml
  .github/workflows/ci_automerge_dependabot.yml
  .github/workflows/ci_cd_updated_master.yml
  .github/workflows/ci_check_dependencies.yml
  .github/workflows/ci_dependabot.yml
  .github/workflows/ci_tests.yml
  .pre-commit-config.yaml
Labels: CI/CD

#360 [Auto-generated] Update dependencies
  .pre-commit-config.yaml
Labels: CI/CD

#366 [Auto-generated] Update dependencies
  .pre-commit-config.yaml
Labels: CI/CD

#370 [Auto-generated] Check & update dependencies (`pyproject.toml`)
  pyproject.toml
Labels: CI/CD, pydantic-v1

#373 [Auto-generated] Check & update dependencies (`pyproject.toml`)
  pyproject.toml
Labels: CI/CD
